print("This is a Madlibs Game with Random Key Outputs")
# numb=int(input("Enter How many times You Want Play:\n"))
# for i in range(numb):
import random
name=("Adnan","Mohammed","Syed","Ibrahim","Nabeel")
field=("Marketing","Computer Science","Bachelor of Arts","BSC","B.Com","Journal")
month=("January", "February", "March", "April", "May", "June"," July"," August", "September", "October", "November"," December")
club=("Ecell","T-Hub","Coding Club","Photography Club","Speaking Club","Entrepreneurship Club")
season=("Summer","Winter","Rainy","Autumn","Spring")
year=("2020","2024","2023","2025")
team=("two","three","Four")
skill=("communication skills","Leadership","Time Management skills","Emotional Intelligence")
tye=("Full time","Part time","Remote","Work From Home")
clus=("Ecell","T-Hub","Coding Club","Photography Club","Speaking Club","Entrepreneurship Club")
names=random.choice(name)
fields=random.choice(field)
months=random.choice(month)
clubs=random.choice(club)
seasons=random.choice(season)
years=random.choice(year)
teams=random.choice(team)
skills=random.choice(skill)
tyes=random.choice(tye)
cluss=random.choice(clus)
madlib=(f"My name is {names}, and I am graduating with my bachelor’s degree in {fields} in {months}. I’m a member of the {clubs} and gained hands-on experience working with the Market Research Center last {seasons}. In {years}, I competed in a business development competition with a team of {teams}, and my team took second place. I’m also a member of {cluss} and maintain our social media pages and outreach website. In the last two years, we’ve increased our membership by 20 percent. I work well on teams, have excellent {skills}, and I’m currently looking for a {tyes} job position.")
print(madlib)